# Generated by Django 6.0.3 on 2026-09-17 18:47

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rescuecenter',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='rescuecenter',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{10,15}$', 'Enter a valid phone number (10-15 digits, optional + prefix).')]),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='donations_d_status_73ca83_idx'),
        ),
    ]
