# Generated by Django 6.0.3 on 2026-09-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_category_options_alter_fooditem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
